name: Test_Ord_Download
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install docker
        run: sudo apt-get install -y docker make

      - name: Get data
        run: make linux_download_ord
